In [1]:
import numpy as np

data_bumper = np.genfromtxt('data/data/output/bumper/bumper_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_bumper = np.delete(data_bumper, 0 , axis = 0)

data_door_ed = np.genfromtxt('data/data/output/door/door_ed_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_door_ed = np.delete(data_door_ed, 0 , axis = 0)
data_door_scratch = np.genfromtxt('data/data/output/door/door_scratch_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_door_scratch = np.delete(data_door_scratch, 0 , axis = 0)

data_fender = np.genfromtxt('data/data/output/fender/fender_ed_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_fender = np.delete(data_fender, 0 , axis = 0)

data_frame_ed = np.genfromtxt('data/data/output/frame/frame_ed_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_frame_ed = np.delete(data_frame_ed, 0 , axis = 0)
data_frame_hd = np.genfromtxt('data/data/output/frame/frame_hd_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_frame_hd = np.delete(data_frame_hd, 0 , axis = 0)
data_frame_sealf = np.genfromtxt('data/data/output/frame/frame_sealf_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_frame_sealf = np.delete(data_frame_sealf, 0 , axis = 0)
data_frame_seamf = np.genfromtxt('data/data/output/frame/frame_seamf_data.csv', delimiter=',', dtype=None, encoding='UTF-8')
data_frame_seamf = np.delete(data_frame_seamf, 0 , axis = 0)

data_1=np.array((data_bumper))
data_2=np.array((data_door_ed))
data_3=np.array((data_door_scratch))
data_4=np.array((data_fender))
data_5=np.array((data_frame_ed))
data_6=np.array((data_frame_hd))
data_7=np.array((data_frame_sealf))
data_8=np.array((data_frame_seamf))

data= np.concatenate((data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8), axis=0)  # axis=0: 배치 축
print(len(data))
print(data)

7381
[['./data/data/source_data/bumper/scratch\\205_101_10_0107f873-8e8a-43d6-94c5-703a77b87e08.jpg'
  '1']
 ['./data/data/source_data/bumper/scratch\\205_101_10_01ba8ed7-8669-4af9-ad2f-7c73a124e769.jpg'
  '1']
 ['./data/data/source_data/bumper/scratch\\205_101_10_0232027f-bfd3-460b-b92d-b14537879e9a.jpg'
  '1']
 ...
 ['./data/data/source_data/frame/Seam_failure\\207_212_20_ff60575c-e8ea-4308-99ba-9ab01930c37a.jpg'
  '0']
 ['./data/data/source_data/frame/Seam_failure\\207_212_20_ff8e6b23-6f57-47d2-b6c2-4fd4eb50e9f7.jpg'
  '0']
 ['./data/data/source_data/frame/Seam_failure\\207_212_20_ffa0491f-762f-41be-8040-007d56f2d01f.jpg'
  '0']]


In [2]:
'''
1. 이미지 4차원으로 불러오기

1-1. 데이터를 불러올 때 일부만 불러오기
1-2. 다른 것도 불러오기

2. 레이블 불러오기

3. x y로 네이밍

'''

#img_resized_1 = img_1.resize((4000,2000))
#a=np.array(img_resized_1)

import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [3]:
from numpy import random

data_num=100

num=random.randint(len(data), size=data_num)

print(num)

[5398 2469 6655 6141 4752 5440 1124 3879 3516 1876 4164 1080  805 6908
  683 6731 3141  895 4041 4357 4340 2806  139 2231 7248 6116 6307 4737
  262 4778 4201 4858 2050 5882 2449 6919  703 3730 2663 3023 6921  820
  593  665 2333 2283 4782 1947 4826 6818 4255 2288 2563 7237 4707  769
 2171 2009 4134 7227 2167 5730 5454  808 2372 3039 3571  724 5594 6725
 4293 2966 6331 5424 6452 2041 5524 7361 4144 7285  600 6652 5115 7238
 5493 2353 4920 5325 4400 1186 6500 4153 5751 7059 4299 1080 1651 1047
 2184 2363]


In [ ]:
from PIL import Image

img_1 = Image.open(data[0,0])

a=np.array(img_1)
a_4=np.expand_dims(a, axis=0)

for i, i2 in enumerate(num):
    img = Image.open(data[i2,0])
    x=np.array(img)
    x_4=np.expand_dims(x, axis=0)
    a_4 = np.concatenate((a_4, x_4), axis=0)  # axis=0: 배치 축
    print(i)


#print(x)
print(a_4.shape)

#100개당 35초

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
(101, 2000, 4000, 3)


In [5]:
print(a_4)

[[[[ 24  29  32]
   [ 24  29  32]
   [ 11  16  19]
   ...
   [154 151 142]
   [152 149 140]
   [150 147 138]]

  [[ 21  26  29]
   [ 19  24  27]
   [ 17  22  25]
   ...
   [152 149 140]
   [150 147 138]
   [150 147 138]]

  [[ 14  19  22]
   [ 17  22  25]
   [ 26  31  34]
   ...
   [150 147 138]
   [149 146 137]
   [149 146 137]]

  ...

  [[ 14  14  14]
   [ 15  15  15]
   [ 14  14  14]
   ...
   [ 27  27  27]
   [ 27  27  27]
   [ 23  23  23]]

  [[ 11  11  11]
   [ 12  12  12]
   [ 14  14  14]
   ...
   [ 29  29  29]
   [ 28  28  28]
   [ 24  24  24]]

  [[ 20  20  20]
   [ 16  16  16]
   [ 16  16  16]
   ...
   [ 28  28  28]
   [ 27  27  27]
   [ 27  27  27]]]


 [[[153 149 150]
   [154 150 151]
   [152 148 149]
   ...
   [135 125 123]
   [143 133 131]
   [140 130 128]]

  [[152 148 149]
   [152 148 149]
   [152 148 149]
   ...
   [137 127 125]
   [145 135 133]
   [141 131 129]]

  [[151 147 148]
   [152 148 149]
   [152 148 149]
   ...
   [140 130 128]
   [144 134 132]
   [144 134